// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['desktop']['App']['ApplyUpdate']();
}

export function CheckForUpdates(arg1) {
  return window['go']['desktop']['App']['CheckForUpdates'](arg1);
}

export function GetCacheSavings(arg1) {
  return window['go']['desktop']['App']['GetCacheSavings'](arg1);
}

export function GetConfig() {
  return window['go']['desktop']['App']['GetConfig']();
}

export function GetContext() {
  return window['go']['desktop']['App']['GetContext']();
}

export function GetPricing() {
  return window['go']['desktop']['App']['GetPricing']();
}

export function GetStats(arg1) {
  return window['go']['desktop']['App']['GetStats'](arg1);
}

export function MinimiseToTray() {
  return window['go']['desktop']['App']['MinimiseToTray']();
}

export function SaveConfig(arg1) {
  return window['go']['desktop']['App']['SaveConfig'](arg1);
}

export function SetDeviceAlias(arg1, arg2) {
  return window['go']['desktop']['App']['SetDeviceAlias'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['desktop']['App']['ShowWindow']();
}
