// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {model} from '../models';
import {config} from '../models';
import {context} from '../models';
import {desktop} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdates(arg1:string):Promise<updater.Release>;

export function GetCacheSavings(arg1:string):Promise<model.CacheSavingsResponse>;

export function GetConfig():Promise<config.AppConfig>;

export function GetContext():Promise<context.Context>;

export function GetPricing():Promise<Array<desktop.PricingEntry>>;

export function GetStats(arg1:string):Promise<model.StatsResponse>;

export function MinimiseToTray():Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function SetDeviceAlias(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;
